---
instance_id: xxx
mas_config_name: xxx
mas_config_scope: system

aiservice_display_name: "AI Service Configuration"
aiservice_url: xxx
aiservice_tenant_id: xxx
aiservice_enabled: true
aiservice_ssl_enabled: true
aiservice_meta_agent_enabled: false

aiservice_api_key: xxx

aiservice_certificate_body: xxx
