{{- if .Values.ibm_entitlement_key }}
---
# Secret — IBM Entitlement pull secret for the postsyncjobs namespace.
# Required so the fvt-gitops Job can pull images from the Artifactory registry.
kind: Secret
apiVersion: v1
metadata:
  name: ibm-entitlement
  annotations:
    argocd.argoproj.io/sync-wave: "1001"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.ibm_entitlement_key }}
{{- end }}
