---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-test-app-a
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "000"
    healthCheckTimeout: "1800"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: '*'
    kind: ServiceAccount
    jsonPointers:
    - /imagePullSecrets
  project: mas
  destination:
      server: 'https://kubernetes.default.svc'
      namespace: 'default'
  source:
    repoURL: https://github.com/ibm-mas/gitops
    path: applications/sync-test-app
    targetRevision: "mascore1839"
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            { "name": "a", "asecret": "<path:arn:aws:secretsmanager:us-east-2:435377327995:secret:fyre-dev/noble3/testsyncapp#hello>"}
        - name: ARGOCD_APP_NAME
          value: droapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true