---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Values.name }}-placeholder"
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "000"
data:
  this-is-just-a-placeholder-resource: "{{ .Values.name }}"
