apiVersion: v2
name: application-admin-rbac
description: Application Admin RBAC for MAS GitOps deployments
type: application
version: 1.0.0

dependencies:
- name: junitreporter
  version: 1.0.0
  repository: "file://../../sub-charts/junitreporter/"
  condition: junitreporter.devops_mongo_uri != ""

# Made with Bob
