---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement
  namespace: {{ tpl .Values.app_namespace . | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "146"
    token: {{ tpl .Values.app_artifactory_token . | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{tpl .Values.app_artifactory_token . | quote }}