---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement
  namespace: "{{ .Values.aiservice_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "146"
    namespace.value: "{{ tpl .Values.global.aiservice_namespace }}"
    dockerconfig.value: "{{ tpl .Values.global.artifactory_token }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ tpl .Values.artifactory_token }}"