---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement
  namespace: "{{ .Values.app_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "146"
    token: "{{ .Values.artifactory_token  }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ .Values.artifactory_token }}"