---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement
  namespace: {{ .Values.aiservice_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "146"
    token: {{ .Values.app_artifactory_token }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.Values.app_artifactory_token }}
