---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement
  namespace: {{ .Values.aiservice_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "146"
    token: {{ tpl .Values.aiservice.app_artifactory_token . | quote}}
    namespace: {{ .Values.aiservice_namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ tpl .Values.aiservice.app_artifactory_token . | quote}}
