
{{- $_cli_image_digest := "sha256:55b5d6dd185503f14c112836a9a4899347d28e7b6545e0b9cf21d87f9526fb40" }}
{{ $aws_secret := "aws"}}

---

kind: Secret
apiVersion: v1
metadata:
  name: {{ $aws_secret }}
  namespace: mas-{{ .Values.ibm_customer_number }}-{{ .Values.subscription_id }}-sls
  annotations:
    argocd.argoproj.io/sync-wave: "105"
type: Opaque
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
data:
  aws_access_key_id: {{ .Values.sm_aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .Values.sm_aws_secret_access_key | b64enc }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: cis-dns-job
  namespace: mas-{{ .Values.ibm_customer_number }}-{{ .Values.subscription_id }}-sls
  annotations:
    argocd.argoproj.io/sync-wave: "113"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    metadata:
      labels:
        app: "postsync-ibm-sls-update-sm-job"
    spec:
      restartPolicy: Never
      containers:
        - name: run
          image: quay.io/ibmmas/cli@{{ $_cli_image_digest }}
          imagePullPolicy: IfNotPresent
          env:
            - name: ACCOUNT_ID
              value: {{ .Values.account_id }}
            - name: CLUSTER_ID
              value: {{ .Values.cluster_id}}
            - name: REGION_ID
              value: {{ .Values.region_id }}
            - name: ICN
              value: '{{ .Values.ibm_customer_number }}'
            - name: SUBSCRIPTION_ID
              value: '{{ .Values.subscription_id }}'
            - name: DOMAIN
              value: '{{ .Values.sls_domain }}'
            - name: CIS_SERVICE_NAME
              value: '{{ .Values.cis_service_name }}'
            - name: CIS_CRN
              value: '{{ .Values.cis_crn }}'
            - name: AVP_TYPE
              value: "aws"
            - name: IBM_CLI_HOME
              value: /tmp/.bluemix 
          volumeMounts:
            - name: aws
              mountPath: /etc/mas/creds/aws
              readOnly: true
          command: ["/bin/sh", "-c"]
          args:
            - |

              set -e

              echo "Reading AWS credentials..." 
              SM_AWS_ACCESS_KEY_ID=$(cat /etc/mas/creds/aws/aws_access_key_id)
              SM_AWS_SECRET_ACCESS_KEY=$(cat /etc/mas/creds/aws/aws_secret_access_key)

              export SM_AWS_REGION=${REGION_ID}

              echo $SM_AWS_REGION


              source /mascli/functions/gitops_utils
              sm_login

              echo "Fetching IBM API key from AWS Secrets Manager"

              SECRET_NAME_CIS="${ACCOUNT_ID}/${CLUSTER_ID}/cis"

              SECRET_JSON=$(aws secretsmanager get-secret-value \
                --secret-id ${SECRET_NAME_CIS} \
                --query SecretString \
                --output text)

              IBM_APIKEY=$(echo ${SECRET_JSON} | jq -r '.ibm_apikey')

               if [[ -z "${IBM_APIKEY}" || "${IBM_APIKEY}" == "null" ]]; then
                echo "Failed to fetch ibm_apikey from ${SECRET_NAME_CIS}"
                exit 1
              fi

              echo "Setting IBM CLI home to writable location..."
              mkdir -p /tmp/.bluemix/plugins        # create plugins directory
              touch /tmp/.bluemix/config.json       # create empty config file
              chmod -R 777 /tmp/.bluemix            # ensure writable by any user

              export IBM_CLI_HOME=/tmp/.bluemix
              export IBM_CLI_CONFIG=/tmp/.bluemix/config.json

              echo "Logging into IBM Cloud..."
              ibmcloud login --apikey ${IBM_APIKEY} -r global

              #echo "Targeting resource group..."
              #ibmcloud target -g Default

              echo "Setting CIS instance..."
              ibmcloud cis instance-set ${CIS_CRN}

              echo "Exporting DOMAIN_NAME..."
              export DOMAIN_NAME=$CIS_SERVICE_NAME

              echo "Fetching DOMAIN_ID..."
              DOMAIN_ID=$(ibmcloud cis domains --output json | jq -r ".[] | select(.name==\"$DOMAIN_NAME\") | .id")


              echo "Creating DNS record..."
               ibmcloud cis dns-record-create "$DOMAIN_ID" \
               --type CNAME \
               --name "SLS.mas-${ICN}-${SUBSCRIPTION_ID}-SLS" \
               --content "apps.cluster.example.com" \
               --proxied false


              echo "DNS record created successfully!"

      volumes:
          - name: aws
            secret:
              secretName: aws       # make sure this Secret exists in the same namespace
              defaultMode: 420
