---
apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
  annotations:
    argocd.argoproj.io/sync-wave: "056"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true,Validate=false"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
spec:
  openshift: true
  cluster:
    name: {{ .Values.cluster_id }}
  zone:
    name: {{ .Values.cluster_id }}
  k8s_sensor:
    deployment:
      enabled: true
  agent:
    keysSecret: instana-agent
    endpointHost: "{{ .Values.instana_agent_operator_endpoint_host }}"
    endpointPort: "{{ .Values.instana_agent_operator_endpoint_port }}"
    env:
      {{- if .Values.instana_agent_operator_env }}
{{ .Values.instana_agent_operator_env | toYaml | indent 6 }}
      {{- end }}
    pod:
      tolerations:
        - effect: NoSchedule
          key: icp4data
          operator: Exists
        - effect: NoSchedule
          key: kmodels
          operator: Exists  
      volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: instana-db2-jks
          mountPath: /jks/
        - name: agent-secrets
          mountPath: /mnt/secrets
          readOnly: true
        - name: argocd-plugin-config
          mountPath: /opt/instana/agent/etc/instana-config-yml/configuration-argocd.yaml
          subPath: config.yaml
        - name: mongodb-plugin-config
          mountPath: /opt/instana/agent/etc/instana-config-yml/configuration-mongodb.yaml
          subPath: config.yaml     
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: instana-db2-jks
          persistentVolumeClaim:
            claimName: instana-db2-jks
        - name: agent-secrets
          secret:
            secretName: instana-agent
        - name: argocd-plugin-config
          configMap:
            name: argocd-plugin
        - name: mongodb-plugin-config
          configMap:
            name: mongodb-plugin
    configuration_yaml: |
{{ include "instana-agent.configuration_yaml" . | indent 6 }}
