{{- if .Values.application_admin_role }}
{{- $_job_name_prefix := "aiservice-subchart" }}
{{- $_cli_image_digest := "sha256:887cc3059a04601241687711df0c03d662931e6719121eec0eb0490001b2c8b9" }}
{{- $_job_config_values := omit .Values "junitreporter" }}
{{- $_job_version := "v1" }}
{{- $_job_hash := print ($_job_config_values | toYaml) $_cli_image_digest $_job_version | adler32sum }}
{{- $_job_name := join "-" (list $_job_name_prefix $_job_hash ) }}
{{- $_job_cleanup_group := cat $_job_name_prefix | sha1sum }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiservice-subchart-job
  namespace: {{ .Values.aiservice_namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aiservice-subchart-job
  namespace: "{{ .Values.aiservice_namespace }}"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "serviceaccounts"]
    verbs: ["get", "list", "patch", "delete"]
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions", "clusterserviceversions"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aiservice-subchart-job
  namespace: "{{ .Values.aiservice_namespace }}"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
subjects:
  - kind: ServiceAccount
    name: postsync-aiservice-migration
    namespace: "{{ .Values.aiservice_namespace }}"
roleRef:
  kind: Role
  name: postsync-aiservice-migration
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aiservice-subchart-job
  namespace: "{{ .Values.aiservice_namespace }}"
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  podSelector:
    matchLabels:
      app: sync-job
  egress:
    - {}
  policyTypes:
    - Egress
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $_job_name }}
  namespace: {{ .Values.aiservice_namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    mas.ibm.com/job-cleanup-group: {{ $_job_cleanup_group }}
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        app: sync-job
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: aiservice-subchart-job
      restartPolicy: OnFailure
      containers:
        - name: aiservice-subchart
          image: quay.io/ibmmas/cli@{{ $_cli_image_digest }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SOURCE_NAMESPACE
              value: "{{ .Values.aiservice_namespace }}"
            - name: TARGET_NAMESPACE
              value: "{{ .Values.tenantNamespace }}"
            - name: ARTIFACTORY_TOKEN
              value: "{{ .Values.artifactory_token }}"
            - name: RELEASE_NAME
              value: "{{ .Release.Name }}"
            
          command:
            - /bin/sh
            - -c
            - |
              set -e
              
              echo pwd
              echo ls
              echo "Installing to $RELEASE_NAME token $ARTIFACTORY_TOKEN"
              helm install $RELEASE_NAME ../../../sub-charts/aiservice/ --set .Values.app_artifactory_token=$ARTIFACTORY_TOKEN

              done
              echo "All secrets copied successfully"
{{- end }}
