{{- if not (empty .Values.ibm_rhoai) }}
---
# IBM Maximo RHOAI (Red Hat OpenShift AI)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai.{{ .Values.cluster.id }}.{{ .Values.instance.id }}
  namespace: {{ .Values.argo.namespace }}
  labels:
    environment: '{{ .Values.account.id }}'
    region: '{{ .Values.region.id }}'
    cluster: '{{ .Values.cluster.id }}'
    instance: '{{ .Values.instance.id }}'
  annotations:
    argocd.argoproj.io/sync-wave: "031"
    healthCheckTimeout: "1800"
    {{- if and .Values.notifications .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-failed.workspace1: {{ .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-succeeded.workspace1: {{ .Values.notifications.slack_channel_id }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "{{ .Values.argo.projects.apps }}"
  destination:
    server: {{ .Values.cluster.url }}
    namespace: "{{ .Values.ibm_rhoai.openshift_namespace }}"
  source:
    repoURL: "{{ .Values.source.repo_url }}"
    path: instance-applications/116-ibm-rhoai
    targetRevision: "{{ .Values.source.revision }}"
    plugin:
      name: {{ .Values.avp.name }} 
      env:
        - name: {{ .Values.avp.values_varname }}
          value: |
            openshift_namespace: "{{ .Values.ibm_rhoai.openshift_namespace }}"
            rhoai_pipeline_name: "{{ .Values.ibm_rhoai.rhoai_pipeline_name }}"
            rhoai_pipeline_namespace: "{{ .Values.ibm_rhoai.rhoai_pipeline_namespace }}"
            rhoai_pipeline_operatorName: "{{ .Values.ibm_rhoai.rhoai_pipeline_operatorName }}"
            rhoai_pipeline_source: "{{ .Values.ibm_rhoai.rhoai_pipeline_source }}"
            rhoai_pipeline_sourceNamespace: "{{ .Values.ibm_rhoai.rhoai_pipeline_sourceNamespace }}"
            serverless_namespace: "{{ .Values.ibm_rhoai.serverless_namespace }}"
            serverless_operator_name: "{{ .Values.ibm_rhoai.serverless_operator_name }}"
            serverless_operator_source: "{{ .Values.ibm_rhoai.serverless_operator_source }}"
            serverless_operator_sourceNamespace: "{{ .Values.ibm_rhoai.serverless_operator_sourceNamespace }}"
            rhoai_OperatorGroup_name: "{{ .Values.ibm_rhoai.rhoai_OperatorGroup_name }}"
            rhoai_name: "{{ .Values.ibm_rhoai.rhoai_name }}"
            rhoai_channel: "{{ .Values.ibm_rhoai.rhoai_channel }}"
            rhoai_namespace: "{{ .Values.ibm_rhoai.rhoai_namespace }}"
            rhoai_applications_namespace: "{{ .Values.ibm_rhoai.rhoai_applications_namespace }}"
            rhoai_monitoring_namespace: "{{ .Values.ibm_rhoai.rhoai_monitoring_namespace }}"
            rhoai_installPlanApproval: "{{ .Values.ibm_rhoai.rhoai_installPlanApproval }}"
            rhoai_source: "{{ .Values.ibm_rhoai.rhoai_source }}"
            rhoai_sourceNamespace: "{{ .Values.ibm_rhoai.rhoai_sourceNamespace }}"

            rhoai_pipeline_channel: "{{ .Values.ibm_rhoai.rhoai_pipeline_channel }}"
            rhoai_pipeline_installplan: "{{ .Values.ibm_rhoai.rhoai_pipeline_installplan }}"
            service_mesh_namespace: "{{ .Values.ibm_rhoai.service_mesh_namespace }}"
            service_mesh_channel: "{{ .Values.ibm_rhoai.service_mesh_channel }}"
            service_mesh_catalog_source: "{{ .Values.ibm_rhoai.service_mesh_catalog_source }}"
            serverless_channel: "{{ .Values.ibm_rhoai.serverless_channel }}"
            authorino_catalog_source: "{{ .Values.ibm_rhoai.authorino_catalog_source }}"
            rhoai_catalog_source: "{{ .Values.ibm_rhoai.rhoai_catalog_source }}"
            rhoai_operator_version: "{{ .Values.ibm_rhoai.rhoai_operator_version }}"
            aiservice_namespace: "{{ .Values.ibm_rhoai.aiservice_namespace }}"
            pull_secret_name: "{{ .Values.ibm_rhoai.pull_secret_name }}"
            mas_aiservice_storage_provider: "{{ .Values.ibm_rhoai.mas_aiservice_storage_provider }}"
            mas_aiservice_storage_accesskey: "{{ .Values.ibm_rhoai.mas_aiservice_storage_accesskey }}"
            mas_aiservice_storage_secretkey: "{{ .Values.ibm_rhoai.mas_aiservice_storage_secretkey }}"
            mas_aiservice_storage_host: "{{ .Values.ibm_rhoai.mas_aiservice_storage_host }}"
            mas_aiservice_storage_port: "{{ .Values.ibm_rhoai.mas_aiservice_storage_port }}"
            mas_aiservice_storage_ssl: "{{ .Values.ibm_rhoai.mas_aiservice_storage_ssl }}"
            mas_aiservice_storage_region: "{{ .Values.ibm_rhoai.mas_aiservice_storage_region }}"
            mas_aiservice_db_host: "{{ .Values.ibm_rhoai.mas_aiservice_db_host }}"
            mas_aiservice_db_port: "{{ .Values.ibm_rhoai.mas_aiservice_db_port }}"
            mas_aiservice_db_user: "{{ .Values.ibm_rhoai.mas_aiservice_db_user }}"
            mas_aiservice_db_database: "{{ .Values.ibm_rhoai.mas_aiservice_db_database }}"
            mas_aiservice_db_secret_key: "{{ .Values.ibm_rhoai.mas_aiservice_db_secret_key }}"
            mas_aiservice_db_secret_name: "{{ .Values.ibm_rhoai.mas_aiservice_db_secret_name }}"
            mas_aiservice_db_secret_value: "{{ .Values.ibm_rhoai.mas_aiservice_db_secret_value }}"
            mas_aiservice_storage_pipelines_bucket: "{{ .Values.ibm_rhoai.mas_aiservice_storage_pipelines_bucket }}"
            primary_storage_class: "{{ .Values.ibm_rhoai.primary_storage_class }}"
            aiservice_rhoai_model_deployment_type: "{{ .Values.aiservice_rhoai_model_deployment_type }}"
            {{- if .Values.custom_labels }}
            custom_labels: {{ .Values.custom_labels | toYaml | nindent 14 }}
            {{- end }}
            junitreporter:
              reporter_name: "ibm-rhoai-{{ .Values.instance.id }}"
              cluster_id: "{{ .Values.cluster.id }}"
              devops_mongo_uri: "{{ .Values.devops.mongo_uri }}"
              devops_build_number: "{{ .Values.devops.build_number }}"
              gitops_version: "{{ .Values.source.revision }}"
        - name: ARGOCD_APP_NAME
          value: rhoai
        {{- if not (empty .Values.avp.secret) }}
        - name: AVP_SECRET
          value: {{ .Values.avp.secret }}
        {{- end }}
  syncPolicy:
    automated:
      {{- if .Values.auto_delete }}
      prune: true
      {{- end }}
      selfHeal: true
    retry:
      limit: 20
    syncOptions:
      - CreateNamespace=true
{{- if .Values.custom_labels }}
    managedNamespaceMetadata:
      labels:
{{ .Values.custom_labels | toYaml | indent 8 }}
{{- end }}
{{- end }}
