---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ibm-operator-catalog-debug
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
data:
  version: Values.mas_catalog_version
  image: Values.mas_catalog_image
