apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-operator-api-key
  namespace: {{ .Values.mongo.namespace }}
  labels:
    atlas.mongodb.com/type: credentials
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  orgId: {{ .Values.mongo.organization_id }}
  publicApiKey: {{ .Values.mongo.publicApiKey }}
  privateApiKey: {{ .Values.mongo.privateApiKey }}

---
kind: Secret
apiVersion: v1
metadata:
  name: aws
  namespace: {{ .Values.mongo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
stringData:
  aws_access_key_id: {{ .Values.aws_access_key_id }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key }}
  aws_default_region: {{ .Values.aws_region }}
type: Opaque

