apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-operator-api-key
  namespace: {{ .Values.mongo.namespace }}
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  orgId: {{ .Values.mongo.organization_id | b64enc | quote }}
  publicApiKey: {{ .Values.mongo.publicApiKey | b64enc | quote }}
  privateApiKey: {{ .Values.mongo.privateApiKey | b64enc | quote }}
