apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupCompliancePolicy
metadata:
  name: {{ .Values.mongo.project_id | lower | replace " " "-" }}-backup-compliance
  namespace: {{ .Values.mongo.namespace }}
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  authorizedEmail: {{ .Values.mongo.backup_compliance.authorized_email }}
  authorizedUserFirstName: {{ .Values.mongo.backup_compliance.authorized_user_first_name }}
  authorizedUserLastName: {{ .Values.mongo.backup_compliance.authorized_user_last_name }}
  pointInTimeEnabled: {{ .Values.mongo.backup_compliance.point_in_time_enabled }}
  restoreWindowDays: {{ .Values.mongo.backup_compliance.restore_window_days }}
  onDemandPolicy:
    retentionUnit: {{ .Values.mongo.backup_compliance.on_demand_policy.retention_unit }}
    retentionValue: {{ .Values.mongo.backup_compliance.on_demand_policy.retention_value }}
  scheduledPolicyItems:
{{- range .Values.mongo.backup_compliance.scheduled_policy_items }}
    - frequencyInterval: {{ .frequency_interval }}
      frequencyType: {{ .frequency_type }}
      retentionUnit: {{ .retention_unit }}
      retentionValue: {{ .retention_value }}
{{- end }}
