apiVersion: atlas.mongodb.com/v1
kind: AtlasPrivateEndpoint
metadata:
  name: {{ .Values.cluster.id }}-private-endpoint
  namespace: {{ .Values.mongo.namespace }}
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  projectRef:
    name: {{ .Values.mongo.project_id }}
  provider: AWS
  region: {{ .Values.region.id }}
