apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: {{ .Values.cluster_id }}-atlas-cluster
  namespace: {{ .Values.mongo.namespace }}
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  externalProjectRef:
    id: {{ .Values.mongo.project_id }}
  deploymentSpec:
    name: {{ .Values.cluster_id }}-cluster
    mongoDBMajorVersion: {{ .Values.mongo.major_db_version | quote }}
    clusterType: REPLICASET
    backupEnabled: {{ .Values.mongo.backup_enabled }}
    pitEnabled: {{ .Values.mongo.pit_enabled }}
    terminationProtectionEnabled: true
    replicationSpecs:
      - numShards: {{ .Values.mongo.shards }}
        zoneName: Zone 1
        
        regionConfigs:
          - providerName: AWS
            regionName: "{{ .Values.aws_region | upper | replace "-" "_" }}"
            priority: 7
            electableSpecs:
              instanceSize: {{ .Values.mongo.instance_size }}
              nodeCount: {{ .Values.mongo.node_count }}
{{- if and .Values.mongo.auto_scaling .Values.mongo.auto_scaling.enabled }}
            autoScaling:
{{- if .Values.mongo.auto_scaling.compute }}
{{- if .Values.mongo.auto_scaling.compute.enabled }}
              compute:
                enabled: {{ .Values.mongo.auto_scaling.compute.enabled }}
                scaleDownEnabled: {{ .Values.mongo.auto_scaling.compute.scale_down_enabled | default true }}
{{- if .Values.mongo.auto_scaling.compute.min_instance_size }}
                minInstanceSize: {{ .Values.mongo.auto_scaling.compute.min_instance_size }}
{{- end }}
{{- if .Values.mongo.auto_scaling.compute.max_instance_size }}
                maxInstanceSize: {{ .Values.mongo.auto_scaling.compute.max_instance_size }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.mongo.auto_scaling.disk_gb }}
{{- if .Values.mongo.auto_scaling.disk_gb.enabled }}
              diskGB:
                enabled: {{ .Values.mongo.auto_scaling.disk_gb.enabled }}
{{- end }}
{{- end }}
{{- end }}
  
{{- if and .Values.mongo.backup_enabled .Values.mongo.cross_region_copy_backup }}
  # Reference to backup schedule
  backupRef:
    name: {{ .Values.cluster_id }}-backup-schedule
{{- end }}
  
  connectionSecret:
    name: mongodb-atlas-operator-api-key
