apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: {{ .Values.cluster.id }}-atlas-cluster
  namespace: {{ .Values.mongo.namespace }}
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  projectRef:
    name: {{ .Values.mongo.project_id | lower | replace " " "-" }}
  
  deploymentSpec:
    name: {{ .Values.cluster.id }}
    mongoDBMajorVersion: {{ .Values.mongo.major_db_version | quote }}
    clusterType: REPLICASET
    backupEnabled: {{ .Values.mongo.backup_enabled }}
    pitEnabled: {{ .Values.mongo.pit_enabled }}
    
    replicationSpecs:
      - numShards: {{ .Values.mongo.shards }}
        zoneName: Zone 1
        
        regionConfigs:
          - providerName: AWS
            regionName: {{ .Values.aws_region | upper | replace "-" "_" }}
            priority: 7
            electableSpecs:
              instanceSize: {{ .Values.mongo.instance_size }}
              nodeCount: {{ .Values.mongo.node_count }}
  
  connectionSecret:
    name: mongodb-atlas-operator-api-key
