{{- if not (empty .Values.nvidia_gpu_operator) }}
---
# IBM Maximo Operator Catalog
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu.{{.Values.account.id}}.{{.Values.region.id}}.{{ .Values.cluster.id }}
  namespace: {{ .Values.argoapp_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "050"
    healthCheckTimeout: "1800"
    {{- if and .Values.notifications .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ .Values.notifications.slack_channel_id }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "{{ .Values.argo_project_apps | default "mas" }}"
  destination:
    server: {{ .Values.cluster.url }}
    namespace: default
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    path: applications/050-nvidia-gpu-operator
    targetRevision: "{{ .Values.source.targetRevision }}"
    plugin:
      env:
        - name: HELM_ARGS
          value: >-
            --set argoapp_namespace={{ .Values.argoapp_namespace }}

            --set nfd_namespace={{ .Values.nvidia_gpu_operator.nfd_namespace }}
            --set nfd_channel={{ .Values.nvidia_gpu_operator.nfd_channel }}
            --set gpu_namespace={{ .Values.nvidia_gpu_operator.gpu_namespace }}
            --set gpu_driver_repository_path={{ .Values.nvidia_gpu_operator.gpu_driver_repository_path }}
            --set gpu_driver_version={{ .Values.nvidia_gpu_operator.gpu_driver_version }}
        - name: ARGOCD_APP_NAME
          value: nvidiagpuapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
{{- end }}