{{- if eq .Values.mongo.action "install" }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-operator.{{ .Values.cluster.id }}
  namespace: {{ .Values.argo.namespace }}
  labels:
    environment: '{{ .Values.account.id }}'
    region: '{{ .Values.region.id }}'
    cluster: '{{ .Values.cluster.id }}'
  annotations:
    argocd.argoproj.io/sync-wave: "062"
    healthCheckTimeout: "1800"
    {{- if and .Values.notifications .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-failed.workspace1: {{ .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-succeeded.workspace1: {{ .Values.notifications.slack_channel_id }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: '*'
    kind: ServiceAccount
    jsonPointers:
    - /imagePullSecrets
  project: "{{ .Values.argo.projects.apps }}"
  destination:
    server: {{ .Values.cluster.url }}
    namespace: {{ .Values.mongo.namespace }}
  source:
    repoURL: "{{ .Values.mongodb_helm_source.repo_url }}"
    path: charts/atlas-operator
    targetRevision: "{{ .Values.mongodb_helm_source.revision }}"
    plugin:
      name: {{ .Values.avp.name }}
      env:
        - name: {{ .Values.avp.values_varname }}
          value: |
            replicaCount: 1

            # Cannot rely on chart dependency in GovCloud since we are 
            # working from an internal clone of the Helm charts hosted in GitLab
            # NOTE: this alone is not sufficient to prevent the AVP plugin from attempting (and failing) to run helm dependency update
            # Instead, the dependency has been removed from the charts in the GovCloud mirror of mongodb/helm-charts
            mongodb-atlas-operator-crds:
              enabled: false

            atlasURI: {{ .Values.mongo.atlasURI }}

            # Override security context for OpenShift - removed runAsUser to let OpenShift assign it
            podSecurityContext:
              runAsNonRoot: true
              runAsUser: null

            # All CRs will be created in the same namespace of the operator
            watchNamespaces:
              - {{ .Values.mongo.namespace }}


        - name: ARGOCD_APP_NAME
          value: atlasoperatorapp
        - name: HELM_ARGS
          value: >-
            --namespace {{ .Values.mongo.namespace }}
        {{- if not (empty .Values.avp.secret) }}
        - name: AVP_SECRET
          value: {{ .Values.avp.secret }}
        {{- end }}
  syncPolicy:
    automated:
      {{- if .Values.auto_delete }}
      prune: true
      {{- end }}
      selfHeal: true
    retry:
      limit: 20
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
