repos:
  - repo: local
    hooks:
      - id: verify-jobs
        name: verify-jobs
        entry: "./build/bin/verify-job-definitions.sh"
        language: script
        types: [file]
        files: \.(yml|yaml)$
        pass_filenames: true
      
      - id: verify-readme-structure
        name: verify-readme-structure
        entry: python build/bin/verify_readme_structure.py
        language: python
        files: README\.md$
        pass_filenames: true
