site_name: MAS GitOps
site_url: https://pages.github.com/ibm-mas/gitops

repo_name: GitHub
repo_url: https://github.com/ibm-mas/gitops
edit_uri: blob/main/docs/

nav:
  - 'Home': index.md
  - 'Architecture':
    - 'Overview': 'architecture.md'
    - 'The Source Repository': helmcharts.md
    - 'The Config Repository': configrepo.md
    - 'The Secrets Vault': secrets.md
  
  - 'Details':
    - 'Mapping Config to MAS Deployments': configtoinstances.md
    - 'Deployment Orchestration': orchestration.md
    - 'Deployment Timings': timings.md
    - 'RBAC Configuration': rbac-configuration.md

  - 'Reference':
    - 'Helm Charts Index': charts-index.md
    - 'Locking Mechanisms': locking-mechanisms.md
    - 'Account Root Application Manifest': accountrootmanifest.md
    - 'Known Limitations': limitations.md

theme:
  name: carbon
  prefix: IBM
  header_nav_items:
    - title: GitOps
      active: true
    - title: Ansible
      url: https://ibm-mas.github.io/ansible-devops/
    - title: CLI
      url: https://ibm-mas.github.io/cli/

markdown_extensions:
  - toc:
      permalink: "¤"
  - admonition
  - attr_list
  - markdown.extensions.footnotes

plugins:
  - search: {}
  - macros
  - include-markdown
  - drawio_file
  - glightbox:
      shadow: true
      caption_position: bottom
      auto_caption: true
      touchNavigation: false
      background: black

