apiVersion: v2
name: mongodb-atlas
description: MongoDB Atlas Operator Resources - Project, Private Endpoint, Deployment, and Database Users
type: application
version: 1.0.0

dependencies:
- name: junitreporter
  version: 1.0.0
  repository: "file://../../sub-charts/junitreporter/"
  condition: junitreporter.devops_mongo_uri != ""