
{{- if (empty .Values.ibm_mas_suite) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-placeholder
  namespace: mas-{{ .Values.instance.id }}-core
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  hello: "world"
{{- end }}
