---
instance_id: xxx
ibm_entitlement_key: xxxx

# Network Routing Configuration (Only for MAS channel 9.2 and onwards)
# Options: "path" or "subdomain" (default: subdomain)
# routing_mode: path

# IngressController name (required when routing_mode is "path")
# ingress_controller_name: default
