---
instance_id: xxx
ibm_entitlement_key: xxxx

# Network Routing Configuration
# Options: "path" or "subdomain" (default: subdomain)
# routing_mode: path

# IngressController name (required when mas_routing_mode is "path")
# ingress_controller_name: default
