---
efs_csi_driver:
  catalog_source: redhat-operators
  catalog_source_namespace: openshift-marketplace
  channel: stable
  subscription_source_namespace: openshift-cluster-csi-drivers
  role_arn: ""

storage_class_definitions: {}