USER-SUPPLIED VALUES:
HANodeConfig:
  nodeRoles: '"master"'
annotationWhitelist:
  containerSpec: ""
  namespace: ""
  workloadController: ""
annotations:
  kubeturbo.io/controllable: "false"
args:
  cleanupSccImpersonationResources: true
  discoveryIntervalSec: 600
  discoverySampleIntervalSec: 60
  discoverySamples: 10
  discoveryTimeoutSec: 180
  discoveryWorkers: 10
  garbageCollectionIntervalMin: 10
  kubelethttps: true
  kubeletport: 10250
  logginglevel: 2
  pre16k8sVersion: false
  sccsupport: '*'
  skipCreatingSccImpersonationResources: false
  stitchuuid: true
daemonPodDetectors:
  namespacePatterns: []
  podNamePatterns: []
discovery:
  chunkSendDelayMillis: 0
  numObjectsPerChunk: 5000
image:
  pullPolicy: IfNotPresent
  related: ""
  repository: icr.io/cpopen/turbonomic/kubeturbo
logging:
  level: 2
nodePoolSize:
  max: 1000
  min: 1
replicaCount: 1
resources: {}
restAPIConfig:
  turbonomicCredentialsSecretName: turbonomic-credentials
roleBinding: turbo-all-binding
roleName: cluster-admin
sdkProtocolConfig:
  registrationTimeoutSec: 300
  restartOnRegistrationTimeout: true
serverMeta:
  turboServer: https://ibm.turbonomic.io
  version: 8.13.4
serviceAccountName: turbo-user
systemWorkloadDetectors:
  namespacePatterns:
  - kube-.*
  - openshift-.*
  - cattle.*
targetConfig:
  targetName: noble7_1613
wiremock:
  enabled: false
  url: wiremock:8080
