---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-credentials
  namespace: {{ .Values.mongodb_namespace | default "mongoce" }}
  annotations:
    argocd.argoproj.io/sync-wave: "024"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
type: Opaque
stringData:
  password: "{{ .Values.admin_password }}"
