---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-operator-api-key
  namespace: {{ .Values.mongo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "04"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
type: Opaque
stringData:
  orgId: "{{ .Values.mongo.organization_id }}"
  publicApiKey: "{{ .Values.mongo.publicApiKey }}"
  privateApiKey: "{{ .Values.mongo.privateApiKey }}"
