---
ibm-entitlement:
km-s3-secret:

app_namespace: 
app_artifactory_token:
app_aiservice_s3_host:
app_aiservice_s3_port:
app_aiservice_s3_ssl:
app_aiservice_s3_region:
app_aiservice_s3_accesskey:
app_aiservice_s3_secretkey:
