---
ibm-entitlement:
km-s3-secret:

app_namespace: 
artifactory_token: "{{ .Values.artifactory_token }}"
aiservice_s3_host: "{{ .Values.aiservice_s3_host }}"
aiservice_s3_port: "{{ .Values.aiservice_s3_port }}"
aiservice_s3_ssl: "{{ .Values.aiservice_s3_ssl }}"
aiservice_s3_region: "{{ .Values.aiservice_s3_region }}"
aiservice_s3_accesskey: "{{ .Values.aiservice_s3_accesskey }}"
aiservice_s3_secretkey: "{{ .Values.aiservice_s3_secretkey }}"