{{ $sa_name    :=  "postsync-custom-sa-update-sm-sa" }}
{{- range $custom_sa_name, $custom_sa_role := $.Values.custom_sa_details }}
---
apiVersion: batch/v1
kind: Job
metadata:
  # Generate the job name by suffixing with a hash of all chart values
  # This is to ensure that ArgoCD will delete and recreate the job if (and only if) anything changes
  # Any change to cluster config will trigger a rerun of the job.
  # The job is idempotent and quick so no real harm in running it when we don't actually need to.
  # The v1 in the name allows use to change this if there is a modification needed that is not in the yaml
  name: postsync-custom-sa-wait-sm-job-v1-{{ $custom_sa_name }}-{{ omit $.Values "junitreporter" | toYaml | adler32sum }}
  namespace: {{ $.Values.custom_sa_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "065"
{{- if $.Values.custom_labels }}
  labels:
{{ $.Values.custom_labels | toYaml | indent 4 }}
{{- end }}
spec:
  ttlSecondsAfterFinished: null
  template:
{{- if $.Values.custom_labels }}
    metadata:
      labels:
{{ $.Values.custom_labels | toYaml | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: run
          image: quay.io/ibmmas/cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 64Mi
          env:
            - name: CUSTOM_SA_NAME
              value: {{ $custom_sa_name }}
            - name: CUSTOM_SA_NAMESPACE
              value: {{ $.Values.custom_sa_namespace }}
          command:
            - /bin/sh
            - -c
            - |

              set -e

              function wait_for_secret {
                SECRET_NS="$1"
                SECRET_PRE="$2"
                RETRIES=${3:-10}
                RETRY_DELAY_SECONDS=${4:-30}

                for (( c=1; c<="${RETRIES}"; c++ )); do

                  echo "... attempt ${c} of ${RETRIES}"
                  
                  SECRET_NAME=$(oc get secrets -n ${SECRET_NS} | grep ${SECRET_PRE}-token | head -1 | cut -d' ' -f1)
                  if [[ ! -z "${SECRET_NAME}" ]]; then
                    echo "SECRET_NAME: $SECRET_NAME"
                    echo "...... success"
                    return 0
                  fi

                  if [[ "${c}" -lt "${RETRIES}" ]]; then
                    echo "...... failed, retry in ${RETRY_DELAY_SECONDS}s"
                    sleep $RETRY_DELAY_SECONDS
                  fi
                done

                echo "...... failed, no attempts remain"
                return 1
              }


              echo ""
              echo "================================================================================"
              echo "Waiting for custom sa secret to be present before continuing (timeout 300s)"
              echo "================================================================================"
              wait_for_secret "${CUSTOM_SA_NAMESPACE}" "${CUSTOM_SA_NAME}"
              
              echo ""
              echo "================================================================================"
              echo "Creating ConfigMap to store custom sa secret name for later use"
              echo "================================================================================"
              oc create configmap custom-sa-config --from-literal=${CUSTOM_SA_NAME}=${SECRET_NAME} 


      restartPolicy: Never
      serviceAccountName: {{ $sa_name }}
  backoffLimit: 4
{{- end }}