{{- $_job_name_prefix := "postsync-tenant-migration" }}
{{- $_cli_image_digest := "sha256:14c852062a8c6149820d9aa7b8315d83f25bb29172b0f318e4fe10af613533f3" }}
{{- $_job_config_values := omit .Values "junitreporter" }}
{{- $_job_version := "v1" }}
{{- $_job_hash := print ($_job_config_values | toYaml) $_cli_image_digest $_job_version | adler32sum }}
{{- $_job_name := join "-" (list $_job_name_prefix $_job_hash ) }}
{{- $_job_cleanup_group := cat $_job_name_prefix | sha1sum }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postsync-tenant-migration
  namespace: {{ .Values.tenantNamespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "postsync-tenant-migration-{{ .Values.tenantNamespace }}"
  namespace: {{ .Values.aiservice_namespace  }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch", "delete"]
  - apiGroups: ["aiservice.ibm.com"]
    resources: ["aiservicetenants"]
    verbs: ["get", "list", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "postsync-tenant-migration-{{ .Values.tenantNamespace }}"
  namespace: {{ .Values.aiservice_namespace  }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
subjects:
  - kind: ServiceAccount
    name: postsync-tenant-migration
    namespace: {{ .Values.tenantNamespace }}
roleRef:
  kind: Role
  name: "postsync-tenant-migration-{{ .Values.tenantNamespace }}"
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postsync-tenant-migration
  namespace: {{ .Values.tenantNamespace  }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch", "delete"]
  - apiGroups: ["aiservice.ibm.com"]
    resources: ["aiservicetenants"]
    verbs: ["get", "list", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postsync-tenant-migration
  namespace: {{ .Values.tenantNamespace  }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
subjects:
  - kind: ServiceAccount
    name: postsync-tenant-migration
    namespace: {{ .Values.tenantNamespace }}
roleRef:
  kind: Role
  name: postsync-tenant-migration
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postsync-tenant-migration
  namespace: "{{ .Values.tenantNamespace }}"
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  podSelector:
    matchLabels:
      app: postsync-job
  egress:
    - {}
  policyTypes:
    - Egress

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $_job_name }}
  namespace: {{ .Values.tenantNamespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    mas.ibm.com/job-cleanup-group: {{ $_job_cleanup_group }}
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
spec:
  activeDeadlineSeconds: 3600 # 1 hour
  template:
    metadata:
      labels:
        app: postsync-job
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: postsync-tenant-migration
      restartPolicy: OnFailure
      containers:
        - name: main
          image: quay.io/ibmmas/cli@{{ $_cli_image_digest }}
          imagePullPolicy: IfNotPresent
          env:
            - name: AISERVICE_NAMESPACE
              value: "{{ .Values.aiservice_namespace }}"
            - name: TENANT_NAMESPACE
              value: "{{ .Values.tenantNamespace }}"
            - name: CATALOG_CHANNEL
              value: "{{ .Values.catalog_channel }}"
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "[INFO] Running post-sync tenant migration at $(date)"
              function clean_up() {
                local clean_up_namespace=${1}
                local cr_namespace=${2}
                readonly API_KEY_SECRET="${TENANT_NAMESPACE}----apikey-secret"
                echo "[INFO] Updating owner reference in secret ${API_KEY_SECRET} in namespace ${cr_namespace}"
                readonly CR_UID=$(oc get aiservicetenant "${TENANT_NAMESPACE}" -n "${cr_namespace}" -o jsonpath='{.metadata.uid}')
                oc get secret "${API_KEY_SECRET}" -n "${cr_namespace}" -o json > /tmp/apikey-secret.json
                jq --arg name "${TENANT_NAMESPACE}" --arg cr_uid "${CR_UID}" \
                  '.metadata.ownerReferences = [{"apiVersion": "aiservice.ibm.com/v1", "kind": "AIServiceTenant", "name": $name, "uid": $cr_uid}]' \
                  /tmp/apikey-secret.json > /tmp/apikey-secret_patched.json
                oc apply -f /tmp/apikey-secret_patched.json

                echo "[INFO] Deleting secret ${API_KEY_SECRET} in namespace ${clean_up_namespace} (if it exists)"
                oc delete secret "${API_KEY_SECRET}" -n "${clean_up_namespace}" --ignore-not-found

                echo "[INFO] Deleting AIServiceTenant ${TENANT_NAMESPACE} in namespace ${clean_up_namespace} (if it exists)"
                if oc get aiservicetenant "${TENANT_NAMESPACE}" -n "${clean_up_namespace}" > /dev/null 2>&1; then
                  # Must patch CR to remove finalizer otherwise we cannot delete it
                  if oc get aiservicetenant "${TENANT_NAMESPACE}" -n "${clean_up_namespace}" -o jsonpath='{.metadata.finalizers}' | grep -q .; then
                    oc patch aiservicetenant "${TENANT_NAMESPACE}" --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]' -n "${clean_up_namespace}"
                  fi
                  oc delete aiservicetenant "${TENANT_NAMESPACE}" -n "${clean_up_namespace}" --ignore-not-found
                fi
              }

              if [[ "${CATALOG_CHANNEL}" == 9.2.* ]]; then
                clean_up ${AISERVICE_NAMESPACE} ${TENANT_NAMESPACE}
              elif [[ "${CATALOG_CHANNEL}" == 9.1.* ]]; then
                clean_up ${TENANT_NAMESPACE} ${AISERVICE_NAMESPACE}
              else
                echo "[INFO] Catalog channel is not 9.1.x or 9.2.x => no migration required"
              fi
              exit 0
