---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: "sync-test-app-{{ .Values.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "000"
  labels:
    argocd.argoproj.io/managed-by: example-argocd