---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Values.name }}-placeholder"
  namespace: "sync-test-app-{{ .Values.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "001"
data:
  this-is-just-a-placeholder-resource: "{{ .Values.asecret }}"
