---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rhoai_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "125"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.rhoai_OperatorGroup_name}}
  namespace: {{ .Values.rhoai_namespace}}
  annotations:
      argocd.argoproj.io/sync-wave: "126"

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: {{ .Values.rhoai_name}}
    namespace: {{ .Values.rhoai_namespace}}
    annotations:
      argocd.argoproj.io/sync-wave: "127"
spec:
    channel: {{ .Values.rhoai_channel}}
    installPlanApproval: {{ .Values.rhoai_installPlanApproval}}
    name: {{ .Values.rhoai_name}}
    source: {{ .Values.rhoai_source}}
    sourceNamespace: {{ .Values.rhoai_sourceNamespace}}
    startingCSV: {{ .Values.rhoai_operator_version }}
