{{- if (eq .Values.dns_provider "cis") }}
{{- $_cli_image_digest := "sha256:4636b74525a46ebd88cd540794e8e23143f0112ea85149f9dfc78d02704ad5a6" }}
{{- $_job_name_prefix := "ibm-dro-dns" }}
{{- $_job_cleanup_group := cat $_job_name_prefix | sha1sum }}
{{- $_job_config_values := omit .Values "junitreporter" }}
{{- $_job_version := "v1" }}
{{- $_job_hash := print ($_job_config_values | toYaml) $_cli_image_digest $_job_version | adler32sum }}
{{- $_job_name := join "-" (list $_job_name_prefix $_job_hash )}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $_job_name }}
  namespace: {{ .Values.dro_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "138"
  labels:
    mas.ibm.com/job-cleanup-group: {{ $_job_cleanup_group }}
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        app: "postsync-ibm-dro-dns-job"
{{- if .Values.custom_labels }}
{{ .Values.custom_labels | toYaml | indent 8 }}
{{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: run
          image: {{ .Values.cli_image_repo | default "quay.io/ibmmas/cli" }}@{{ $_cli_image_digest }}
          imagePullPolicy: IfNotPresent
          env:
            - name: ACCOUNT_ID
              value: {{ .Values.account_id }}
            - name: CLUSTER_ID
              value: {{ .Values.cluster_id }}
            - name: REGION_ID
              value: {{ .Values.region_id }}
            - name: DRO_PUBLIC_DOMAIN
              value: '{{ .Values.dro_public_domain }}'
            - name: CIS_CRN
              value: '{{ .Values.cis_crn }}'
            - name: AVP_TYPE
              value: "aws"
            - name: IBMCLOUD_HOME
              value: /tmp/bluemix
          volumeMounts:
            - name: aws
              mountPath: /etc/mas/creds/aws
              readOnly: true
          command: ["/bin/sh", "-c"]
          args:
            - |

              set -e

              echo "Reading AWS credentials..."
              SM_AWS_ACCESS_KEY_ID=$(cat /etc/mas/creds/aws/aws_access_key_id)
              SM_AWS_SECRET_ACCESS_KEY=$(cat /etc/mas/creds/aws/aws_secret_access_key)

              export SM_AWS_REGION=${REGION_ID}

              source /mascli/functions/gitops_utils
              sm_login

              echo "Fetching IBM API key from AWS Secrets Manager"
              SECRET_NAME_CIS="${ACCOUNT_ID}/${CLUSTER_ID}/cis"

              SECRET_JSON=$(aws secretsmanager get-secret-value \
                --secret-id ${SECRET_NAME_CIS} \
                --query SecretString \
                --output text)

              echo "Fetching OCP ingress from AWS Secrets Manager"
              export PUBLIC_ELB_DNS_NAME_FILE="/tmp/public-elb-dns-name-file.json"
              sm_get_secret_file ${ACCOUNT_ID}/${CLUSTER_ID}/public-elb ${PUBLIC_ELB_DNS_NAME_FILE}
              export OCP_INGRESS=$(jq -r .dns ${PUBLIC_ELB_DNS_NAME_FILE})

              IBM_APIKEY=$(echo ${SECRET_JSON} | jq -r '.ibm_apikey')

              if [[ -z "${IBM_APIKEY}" || "${IBM_APIKEY}" == "null" ]]; then
                echo "Failed to fetch ibm_apikey from ${SECRET_NAME_CIS}"
                exit 1
              fi

              if [[ -z "${OCP_INGRESS}" || "${OCP_INGRESS}" == "null" ]]; then
                echo "Failed to fetch dns value from public-elb secret"
                exit 1
              fi

              echo "Setting IBM CLI home to writable location..."
              export IBMCLOUD_HOME=/tmp/bluemix
              mkdir -p ${IBMCLOUD_HOME}

              echo "Disabling version check..."
              ibmcloud config --check-version=false

              echo "Logging into IBM Cloud..."
              ibmcloud login --apikey ${IBM_APIKEY} -r us-east

              echo "Installing CIS plugin..."
              ibmcloud plugin install cis -f

              echo "Setting CIS instance..."
              ibmcloud cis instance-set ${CIS_CRN}

              echo "Fetching DOMAIN_ID..."
              DOMAIN_ID=$(ibmcloud cis domains --output json | jq -r ".[] | select(.name==\"${DRO_PUBLIC_DOMAIN}\") | .id")

              echo "domain id : ${DOMAIN_ID}"

              if [[ -z "${DOMAIN_ID}" || "${DOMAIN_ID}" == "null" ]]; then
                echo "ERROR: Could not find Domain ID for name: ${DRO_PUBLIC_DOMAIN}"
                exit 1
              fi

              RECORD_NAME="dro.${CLUSTER_ID}"
              echo "RECORD_NAME: ${RECORD_NAME}"
              
              echo "Creating DNS record..."
              CREATE_OUTPUT=$(ibmcloud cis dns-record-create "${DOMAIN_ID}" \
                --type CNAME \
                --name "${RECORD_NAME}" \
                --content "${OCP_INGRESS}" \
                --proxied false 2>&1 || true)

              if echo "${CREATE_OUTPUT}" | grep -qi "already exists\|duplicate"; then
                echo "DNS record already exists."
                exit 0
              elif echo "${CREATE_OUTPUT}" | grep -qi "OK\|Created\|success"; then
                echo "DNS record created successfully!"
              else
                echo "ERROR: DNS record creation failed"
                echo "${CREATE_OUTPUT}"
                exit 1
              fi

      volumes:
        - name: aws
          secret:
            secretName: aws
            defaultMode: 420
{{- end }}

