{{- if (eq .Values.dns_provider "cis") }}
{{- if .Values.dro_public_domain }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "139"
  name: dro-tls-cert
  namespace: "{{ .Values.dro_namespace }}"
spec:
  secretName: dro-tls-secret
  issuerRef:
    name: "{{ .Values.cluster_id }}-{{ .Values.dns_provider }}-le-prod"
    kind: ClusterIssuer
  commonName: dro.{{ .Values.cluster_id }}.{{ .Values.dro_public_domain }}
  dnsNames:
    - dro.{{ .Values.cluster_id }}.{{ .Values.dro_public_domain }}
  privateKey:
    rotationPolicy: Always
{{- end }}
{{- end }}