---
openshift_namespace: "openshift-operators"
rhoai_pipeline_channel: "latest"
rhoai_pipeline_installplan: "Automatic"
rhoai_namespace: "redhat-ods-operator"
rhoai_applications_namespace: "redhat-ods-applications"
rhoai_monitoring_namespace: "redhat-ods-monitoring"
service_mesh_namespace: "openshift-operators"
service_mesh_channel: "stable"
service_mesh_catalog_source: "redhat-operators"
service_mesh_sourceNamespace: "openshift-marketplace"
serverless_channel: "stable"
authorino_catalog_source: "community-operators"
rhoai_channel: "stable"
rhoai_catalog_source: "redhat-operators"
rhoai_operator_version: "rhods-operator.2.25.4"

#RHOAI_Pipeline_operator
rhoai_pipeline_name: "openshift-pipelines-operator"
rhoai_pipeline_namespace: "openshift-operators"
rhoai_pipeline_operatorName: "openshift-pipelines-operator-rh"
rhoai_pipeline_source: "redhat-operators"
rhoai_pipeline_sourceNamespace: "openshift-marketplace"

#Serverless Operator
serverless_namespace: "openshift-serverless"
serverless_operator_name: "serverless-operator"
serverless_operator_source: "redhat-operators"
serverless_operator_sourceNamespace: "openshift-marketplace"

#RHOAI Operator
rhoai_OperatorGroup_name: "redhat-ods-operator-group"
rhoai_name: "rhods-operator"
rhoai_installPlanApproval: "Automatic"
rhoai_source: "redhat-operators"
rhoai_sourceNamespace: "openshift-marketplace"

namespace: "openshift-operators"
channel: "latest"
operatorName: "openshift-pipelines-operator-rh"
source: "redhat-operators"
sourceNamespace: "openshift-marketplace"

aiservice_namespace: "mas-sremat-aiservice"
pull_secret_name: "ibm_entitlement"

# Storage vars
mas_aiservice_storage_provider: "aws"
mas_aiservice_storage_accesskey: "aiservice_storage_accesskey"
mas_aiservice_storage_secretkey: "aiservice_storage_secretkey"
mas_aiservice_storage_host: "mas_aiservice_storage_host"
mas_aiservice_storage_port: "mas_aiservice_storage_port"
mas_aiservice_storage_ssl: "mas_aiservice_storage_ssl"
mas_aiservice_storage_region: "mas_aiservice_storage_region"
mas_aiservice_storage_pipelines_bucket: "mas_aiservice_storage_pipelines_bucket"
primary_storage_class: "defaultStorageClasses"
