apiVersion: v2
name: mongodb-ce
description: MongoDB Community Operator and Instance
type: application
version: 1.0.0

dependencies:
- name: junitreporter
  version: 1.0.0
  repository: "file://../../sub-charts/junitreporter/"
  condition: junitreporter.devops_mongo_uri != ""
