---
# Common cluster values
account_id: ""
region_id: ""
cluster_id: ""
cluster_admin_role: true
run_sync_hooks: true
cli_image_repo: ""
sm_aws_access_key_id: ""
sm_aws_secret_access_key: ""

# MongoDB ReplicaSet settings
mongodb_namespace: "mongoce"
mongodb_instance_name: "mas-mongo-ce"
mongodb_version: "7.0.12"
mongodb_members: 3

# Storage
storage_size: "10Gi"
logs_storage_size: "1Gi"
storage_class: ""

# Resources
resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"
