---
# Common cluster values
account_id: ""
region_id: ""
cluster_id: ""
cluster_admin_role: true
run_sync_hooks: true
cli_image_repo: ""
sm_aws_access_key_id: ""
sm_aws_secret_access_key: ""

# Operator settings
mongodb_operator_channel: "v0.7"
mongodb_operator_install_plan: "Automatic"
mongodb_operator_source: "community-operators"
mongodb_operator_source_namespace: "openshift-marketplace"

# MongoDB ReplicaSet settings
mongodb_namespace: "mongoce"
mongodb_instance_name: "mas-mongo-ce"
mongodb_version: "7.0.5"
mongodb_members: 3

# Credentials & Storage
admin_password: "ChangeMe123!"
storage_size: "10Gi"
storage_class: ""

# Resources
resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"
