---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io1
  annotations:
    argocd.argoproj.io/sync-wave: "064"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
provisioner: kubernetes.io/aws-ebs
parameters:
  encrypted: 'true'
  iopsPerGB: '100'
  type: io1
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate