{{- if and .Values.application_admin_role .Values.db2_license_file }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "db2u-license-{{ .Values.db2_instance_name }}"
  namespace: "{{ .Values.db2_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "121"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
type: Opaque
stringData:
  db2u-lic: >-
    {{ .Values.db2_license_file }}
{{- end }}
