{{- if .Values.application_admin_role }}
{{- if and .Values.db2_backup_bucket_name (not (contains "sdb" .Values.db2_instance_name)) }}

{{- /*
Use the build/bin/set-cli-image-digest.sh script to update this value across all charts.
*/}}
{{- $_cli_image_digest := "sha256:db6dba0d58592a1bbed459bbe8285316c36d0d8c0bf8b39e1d0f910b3400f441" }}

#
# CronJob for DB2 Audit Log Extraction
# Runs every 5 minutes to archive and extract DB2 audit logs as DEL/ASC
# files, upload them to the audit-log-<app>/<YYYYMMDD>/ folder inside the
# backup bucket, then removes local copies.
#
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: "db2-audit-extract-{{ .Values.db2_instance_name }}"
  namespace: "{{ .Values.db2_namespace }}"
  labels:
    parent: cronjob
    cosBucket: "{{ .Values.db2_backup_bucket_name }}"
    db2pod: "c-{{ .Values.db2_instance_name }}-db2u-0"
    mas.ibm.com/instanceId: "{{ .Values.instance_id }}"
  annotations:
    argocd.argoproj.io/sync-wave: "132"
spec:
  # Run every day 1 AM
  schedule: '0 1 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: cronjob
        spec:
          containers:
            - name: "db2-audit-extract-{{ .Values.db2_instance_name }}"
              image: {{ .Values.cli_image_repo | default "quay.io/ibmmas/cli" }}@{{ $_cli_image_digest }}
              command:
                - oc
                - rsh
                - "c-{{ .Values.db2_instance_name }}-db2u-0"
                - su
                - -lc
                - "{{ .Values.db2_instance_home_path }}/bin/db2AuditExtract.sh {{ .Values.mas_application_id }} {{ .Values.db2_dbname }}"
                - db2inst1
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          serviceAccountName: "account-{{ .Values.db2_namespace }}-{{ .Values.db2_instance_name }}"
  successfulJobsHistoryLimit: 30
  failedJobsHistoryLimit: 10
{{- end }}
{{- end }}
