{{- if .Values.application_admin_role }}
{{- if .Values.db2_manual_cert.enabled }}
{{- if and .Values.db2_manual_cert.tls_crt .Values.db2_manual_cert.tls_key }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "db2u-manual-certificate-{{ .Values.db2_instance_name }}"
  namespace: "{{ .Values.db2_namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "121"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
data:
  tls.crt: {{ .Values.db2_manual_cert.tls_crt }}
  tls.key: {{ .Values.db2_manual_cert.tls_key }}
{{- if .Values.db2_manual_cert.ca_crt }}
  ca.crt: {{ .Values.db2_manual_cert.ca_crt }}
{{- end }}
type: kubernetes.io/tls
{{- end }}
{{- end }}
{{- end }}
