---
instance_id: xxx
jdbc_instance_username: xxx
jdbc_instance_password: xxx
rds_admin_db_name : rdsadmin
jdbc_connection_url: xxx

# Multiple certificates can be added to the JdbcCfg
# Each certificate should have a unique alias
jdbc_certificates:
  - alias: "rds1"
    crt: "-----BEGIN CERTIFICATE-----\nMIID...\n-----END CERTIFICATE-----"
  - alias: "rds2"
    crt: "-----BEGIN CERTIFICATE-----\nMIID...\n-----END CERTIFICATE-----"
  - alias: "rds3"
    crt: "-----BEGIN CERTIFICATE-----\nMIID...\n-----END CERTIFICATE-----"

jdbc_instance_name: xxx

mas_config_name: xxx