---
sm_aws_access_key_id: xxx
sm_aws_secret_access_key: xxx
instana_agent_operator_channel: 'stable'
instana_agent_operator_key: xxx
instana_agent_operator_endpoint_host: xxx
instana_agent_operator_endpoint_port: '443'
instana_agent_operator_env: {}
instana_agent_operator_jks_storage_class: xxx

# ArgoCD Plugin
instana_agent_operator_argocd_plugin_enabled: false
instana_agent_operator_argocd_insecure_skip_tls: false
instana_agent_operator_argocd_url: ""
instana_agent_operator_argocd_clusters: []
instana_agent_operator_argocd_poll_rate_sec: 10
