image: python:3.11-slim

db2:
  host: your-db2-instance.rds.amazonaws.com
  port: 50000
  dbname: BLUDB
  user: db2inst1
  password: yourpassword

scriptConfigMapName: db2-init-script
mas_application_id: manage