image: python:3.11-slim

db2-rds:
  host: xxx
  port: xxx
  dbname: xxx
  user: xxx
  password: xxx

db2_rds_instance_name: dbs-rds-inst1-manage
scriptConfigMapName: db2-init-script
mas_application_id: XXX