image: python:3.11-slim

ibm_dbs_rds_databases:
  - host: db1.example.com
    port: "5432"
    name: database1
    username: user1
    password: pass1
    mas_application_id: XXX
    db2_rds_instance_name: dbs-rds-inst1-manage

scriptConfigMapName: db2-init-script
mas_application_id: XXX