---

fvt-gitops-runner:
  enabled: true
  devops_mongo_uri: ""
  devops_build_number: ""
  instance_id: ""
  cluster_id: ""
  workspace_id: "masdev"
  test_suite: "suite"
  gitops_version: ""
  fvt_gitops_image_repo: "docker-na-public.artifactory.swg-devops.com/wiotp-docker-local/mas-devops/fvt-gitops"
  fvt_gitops_image_tag: "v1.0.4"
  argo_namespace: "openshift-gitops"
  custom_labels: {}
