---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scriptConfigMapName | quote }}-backup
  annotations:
    argocd.argoproj.io/sync-wave: "137"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
data:
  rds-db2-backup.py: |
    #!/usr/bin/env python3
    """
    RDS DB2 Backup Script
    Performs FULL or INCREMENTAL backups of RDS DB2 database to S3
    """
   