apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
  annotations:
    argocd.argoproj.io/sync-wave: "135"
type: Opaque
data:
  db2_endpoint: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:mcspsre-1/rds-db2-endpoint-config-PMJ0fd#db2_endpoint>
  db2_port: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:mcspsre-1/rds-db2-endpoint-config-PMJ0fd#db2_port>
  db2_name: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:mcspsre-1/rds-db2-endpoint-config-PMJ0fd#db2_name>
  username: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:mcspsre-1/rds-db2-endpoint-config-PMJ0fd#username>
  password: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:mcspsre-1/rds-db2-endpoint-config-PMJ0fd#password>
