apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: my-db-secret
    creationPolicy: Owner
  data:
    - secretKey: db2_endpoint
      remoteRef:
        key: mcspsre-1/rds-db2-endpoint-config-PMJ0fd
        property: db2_endpoint
    - secretKey: db2_port
      remoteRef:
        key: mcspsre-1/rds-db2-endpoint-config-PMJ0fd
        property: db2_port
    - secretKey: db2_name
      remoteRef:
        key: mcspsre-1/rds-db2-endpoint-config-PMJ0fd
        property: db2_name
    - secretKey: username
      remoteRef:
        key: mcspsre-1/rds-db2-endpoint-config-PMJ0fd
        property: username
    - secretKey: password
      remoteRef:
        key: mcspsre-1/rds-db2-endpoint-config-PMJ0fd
        property: password
