{{- if not (empty .Values.ibm_sls) }}
---
# IBM Maximo Operator Catalog
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sls.{{.Values.account.id}}.{{.Values.region.id}}.{{ .Values.cluster.id }}.{{ .Values.instance.id }}
  namespace: {{ .Values.argoapp_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    {{- if and .Values.notifications .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ .Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ .Values.notifications.slack_channel_id }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: '*'
    kind: ServiceAccount
    jsonPointers:
    - /imagePullSecrets
  project: "{{ .Values.argo_project_apps | default "mas" }}"
  destination:
    server: {{ .Values.cluster.url }}
    namespace: default
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    path: applications/100-ibm-sls
    targetRevision: "{{ .Values.source.targetRevision }}"
    plugin:
      env:
        - name: HELM_ARGS
          value: |-
            --set argoapp_namespace={{ .Values.argoapp_namespace }}
            
            --set aws_access_key_id={{ .Values.ibm_sls.sm_aws_access_key_id }}
            --set aws_secret_access_key={{ .Values.ibm_sls.sm_aws_secret_access_key }}
            --set aws_region={{ .Values.ibm_sls.sm_aws_region }}
            
            --set account_id={{ .Values.ibm_sls.account_id }}
            --set cluster_id={{ .Values.ibm_sls.cluster_id }}
            --set docdb_host={{ .Values.ibm_sls.docdb_host }}
            --set docdb_port={{ .Values.ibm_sls.docdb_port }}
            --set mongodb_provider={{ .Values.ibm_sls.mongodb_provider }}
            --set user_action={{ .Values.ibm_sls.user_action }}
            --set mas_instance_id={{ .Values.ibm_sls.mas_instance_id }}
            --set docdb_master_username={{ .Values.ibm_sls.docdb_master_username }}
            --set docdb_master_username={{ .Values.ibm_sls.docdb_master_username }}
            --set docdb_master_password={{ .Values.ibm_sls.docdb_master_password }}
            --set docdb_master_info={{ .Values.ibm_sls.docdb_master_info }}
            --set sls_mongo_username={{ .Values.ibm_sls.sls_mongo_username }}
            --set sls_mongo_password={{ .Values.ibm_sls.sls_mongo_password }}
            --set sls_channel={{ .Values.ibm_sls.sls_channel }}
            --set ibm_entitlement_key={{ .Values.ibm_sls.ibm_entitlement_key }}
            --set sls_mongo_secret_name={{ .Values.ibm_sls.sls_mongo_secret_name }}
            --set sls_entitlement_file={{ .Values.ibm_sls.sls_entitlement_file }}
            --set icr_cp_open={{ .Values.ibm_sls.icr_cp_open }}
            --set run_sync_hooks={{ .Values.ibm_sls.run_sync_hooks }}

            --set-json mongo_spec='{{ .Values.ibm_sls.mongo_spec | toRawJson }}'

        - name: ARGOCD_APP_NAME
          value: slsapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
{{- end }}
