{{- /*
When inside the range loop below, make sure you prefix any references to chart values NOT under .Values.ibm_db2u_databases with $.
For example: {{ $.Values.account.id }} (instead of {{ .Values.account.id }} )
*/}}

{{- range $i, $value := .Values.ibm_db2u_databases }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "db2-db.{{ $.Values.account.id }}.{{ $.Values.region.id }}.{{ $.Values.cluster.id }}.{{ $.Values.instance.id }}.{{ $value.mas_application_id }}"
  namespace: {{ $.Values.argoapp_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "120"
    {{- if and $.Values.notifications $.Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ $.Values.notifications.slack_channel_id }}
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ $.Values.notifications.slack_channel_id }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    cloud: aws
    environment: '{{ $.Values.account.id }}'
    region: '{{ $.Values.region.id }}'
    cluster: '{{ $.Values.cluster.id }}'
    instance: '{{ $.Values.instance.id }}'
spec:
  project: "{{ $.Values.argo_project_apps | default "mas" }}"
  destination:
    server: {{ $.Values.cluster.url }}
    namespace: default
  source:
    repoURL: "{{ $.Values.source.repoURL }}"
    path: applications/120-ibm-db2u-database
    targetRevision: "{{ $.Values.source.targetRevision }}"
    plugin:
      env:
        - name: HELM_ARGS
          value: |
            --set aws_access_key_id={{ $value.sm.aws_access_key_id }}
            --set aws_secret_access_key={{ $value.sm.aws_secret_access_key }}
            --set account.id={{ $value.account.id }}
            --set region.id={{ $value.region.id }}
            --set cluster.id={{ $value.cluster.id }}
            --set instance.id={{ $value.instance.id }}
            --set mas_application_id={{ $value.mas_application_id.id }}
            --set db2_instance_name={{ $value.db2_instance_name }}
            --set db2_namespace={{ $value.db2_namespace }}
            --set cluster_domain={{ $value.cluster_domain }}
            --set db2_version={{ $value.db2_version }}
            --set db2_num_pods={{ $value.db2_num_pods }}
            --set db2_dbname={{ $value.db2_dbname }}
            --set db2_table_org={{ $value.db2_table_org }}
            --set-json db2_database_db_config={{ $value.db2_database_db_config | toRawJson }}
            --set-json db2_instance_registry={{ $value.db2_instance_registry | toRawJson }}
            --set-json db2_instance_dbm_config={{ $value.db2_instance_dbm_config | toRawJson }}
            --set db2_mln_count={{ $value.db2_mln_count }}
            --set db2_cpu_requests={{ $value.db2_cpu_requests }}
            --set db2_memory_requests={{ $value.db2_memory_requests }}
            --set db2_cpu_limits={{ $value.db2_cpu_limits }}
            --set db2_memory_limits={{ $value.db2_memory_limits }}
            --set db2_meta_storage_class={{ $value.db2_meta_storage_class }}
            --set db2_meta_storage_accessmode={{ $value.db2_meta_storage_accessmode }}
            --set db2_meta_storage_size={{ $value.db2_meta_storage_size }}
            --set db2_data_storage_class={{ $value.db2_data_storage_class }}
            --set db2_data_storage_accessmode={{ $value.db2_data_storage_accessmode }}
            --set db2_data_storage_size={{ $value.db2_data_storage_size }}
            --set db2_backup_storage_class={{ $value.db2_backup_storage_class }}
            --set db2_backup_storage_accessmode={{ $value.db2_backup_storage_accessmode }}
            --set db2_backup_storage_size={{ $value.db2_backup_storage_size }}
            --set db2_logs_storage_accessmode={{ $value.db2_logs_storage_accessmode }}
            --set db2_logs_storage_size={{ $value.db2_logs_storage_size }}
            --set db2_logs_storage_class={{ $value.db2_logs_storage_class }}
            --set db2_temp_storage_accessmode={{ $value.db2_temp_storage_accessmode }}
            --set db2_temp_storage_size={{ $value.db2_temp_storage_size }}
            --set db2_temp_storage_class={{ $value.db2_temp_storage_class }}
        - name: ARGOCD_APP_NAME
          value: "db2dbapp-{{ $value.mas_application_id }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: 'db2u.databases.ibm.com'
      kind: Db2uCluster
      jsonPointers:
      - /spec/environment/database/ssl/secretName
{{- end }}